
version: 2

sources:
    - name: staging
      #For bigquery:
      database: certain-tangent-339418

      # For postgres:
      # database: production

      schema: dbt

      # loaded_at_field: record_loaded_at
      tables:
        - name: green_tripdata
        - name: yellow_tripdata
        - name: fhv_tripdata
         # freshness:
           # error_after: {count: 6, period: hour}

